name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger this action on commits to the main branch
permissions:
  contents: read  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Sync the local files to the S3 bucket
    - name: Deploy to S3
      run: |
        aws s3 sync ./ s3://voxel-labs.dev --delete
